services:
  booking-postgres:
    container_name: booking_postgres
    image: postgres:17
    restart: always
    environment:
      POSTGRES_DB: booking_service_db
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
    ports:
      - "5434:5432"
    volumes:
      - booking-postgres-data:/var/lib/postgresql/data

  auth-postgres:
    container_name: auth_postgres
    image: postgres:17
    restart: always
    environment:
      POSTGRES_DB: auth_service_db
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
    ports:
      - "5436:5432"
    volumes:
      - auth-postgres-data:/var/lib/postgresql/data

volumes:
  booking-postgres-data:
  auth-postgres-data: